shipStats = {
    frigates:{
        frigate1:{
            hullCoeficent:1,
            shieldsCoeficent:1,
            speed:10,
            rotationSpeed:1,
            mainCannonDamage:10,
            mainCannonPosition:{
                x:0,
                y:0,
                z:0
            },
            turrets:[
            {
                position:{
                    x:0,
                    y:0,
                    z:0
                },
                damage:10,
                rotationSpeed:1
            }
            ]
        }
    }
}